"""Experience replay buffer for RL training.

Stores (state, policy, value) triples generated by self-play.
Fixed capacity with automatic FIFO eviction: when full, the oldest
position is silently dropped to make room for the newest one.

Sampling randomly from a large buffer breaks the temporal correlation
between consecutive positions, which stabilises gradient updates.
"""

from __future__ import annotations

import random
from collections import deque
from typing import List, Tuple

import numpy as np
import torch

from chess_rl.config import BATCH_SIZE, DEVICE, REPLAY_BUFFER_SIZE
from chess_rl.training.self_play import Sample


class ReplayBuffer:
    """Fixed-capacity FIFO experience replay store.

    Args:
        capacity: Maximum number of (state, policy, value) triples to keep.
                  Oldest entries are evicted automatically when the buffer
                  reaches capacity.  Default: 500,000 positions.
    """

    def __init__(self, capacity: int = REPLAY_BUFFER_SIZE) -> None:
        self._buffer: deque = deque(maxlen=capacity)
        self.capacity = capacity

    # ── Insertion ──────────────────────────────────────────────────────────

    def push(
        self,
        state: np.ndarray,
        policy: np.ndarray,
        value: float,
    ) -> None:
        """Add a single (state, policy, value) triple to the buffer.

        Args:
            state:  Board encoding of shape (119, 8, 8), float32.
            policy: MCTS visit-count distribution of shape (4096,), float32.
            value:  Game outcome from the moving player's perspective (±1 / 0).
        """
        self._buffer.append((state, policy, float(value)))

    def push_many(self, samples: List[Sample]) -> None:
        """Add a list of (state, policy, value) triples in one call.

        Args:
            samples: Output of play_one_game() or generate_games().
        """
        for state, policy, value in samples:
            self.push(state, policy, value)

    # ── Sampling ───────────────────────────────────────────────────────────

    def sample(
        self,
        batch_size: int = BATCH_SIZE,
        device: str = DEVICE,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return a random batch of positions as PyTorch tensors.

        Samples without replacement up to min(batch_size, len(buffer)).

        Args:
            batch_size: Number of positions to draw.
            device:     Torch device for the returned tensors.

        Returns:
            states:   float32 tensor of shape (B, 119, 8, 8).
            policies: float32 tensor of shape (B, 4096).
            values:   float32 tensor of shape (B,).
        """
        n = min(batch_size, len(self._buffer))
        batch = random.sample(self._buffer, n)

        states, policies, values = zip(*batch)

        states_t = torch.tensor(
            np.stack(states), dtype=torch.float32, device=device
        )
        policies_t = torch.tensor(
            np.stack(policies), dtype=torch.float32, device=device
        )
        values_t = torch.tensor(
            list(values), dtype=torch.float32, device=device
        )

        return states_t, policies_t, values_t

    # ── Queries ────────────────────────────────────────────────────────────

    def __len__(self) -> int:
        """Current number of positions stored."""
        return len(self._buffer)

    def is_ready(self, batch_size: int = BATCH_SIZE) -> bool:
        """True if the buffer contains at least batch_size positions."""
        return len(self._buffer) >= batch_size
